### ISSUE TITLE
Table structure and navigation bar missed

### ISSUE THREAD

**Issue by chelobotix** [FevenSeyfu/Awesome-Books#6]
Good job! Your awesome book looks "awesome".
Reviewing your code, I found these issues in the order for you can improve it.

- Please consider changing the table in which you put the books to a GridLayout, a more modern structure.

![image](https://user-images.githubusercontent.com/65084923/213719267-689edc5c-911a-4d07-a6d6-ca67ebf33c04.png)

- I think you just forgot to add navigation and a footer in the updated project.

**Comment by FevenSeyfu** [comment]
Thank you for your feedback, the added feature was not merged to the main branch, that's why the layout wasn't displayed It is now fixed.
